use dotenv::{dotenv, var};
use std::fs::File;
use std::io::Write;

fn pub_const_fmt(key: &str) -> String {
    let value = var(key).unwrap();

    format!(
        "pub const {}: &'static str = \"{}\";\n",
        key,
        value.replace('"', "\\\"")
    )
}

fn main() {
    println!("cargo:rerun-if-changed=../.env");
    let wasm_path = "../wlrs-wasm/src/env.rs";
    let server_path = "src/env.rs";
    let mut f_wasm = File::create(wasm_path).unwrap();
    let mut f_server = File::create(server_path).unwrap();

    // use the dotenv crate to get the .env values
    dotenv().ok();
    f_wasm
        .write_all(b"// This file is automatically generated by build.rs\n\n")
        .unwrap();
    f_server
        .write_all(b"// This file is automatically generated by build.rs\n\n")
        .unwrap();

    f_server
        .write_all(pub_const_fmt("WLRS_SERVER_ADDR").as_bytes())
        .unwrap();
    f_wasm
        .write_all(pub_const_fmt("WLRS_WEBSOCKET_ADDR").as_bytes())
        .unwrap();
    f_server
        .write_all(pub_const_fmt("RCON_PASS").as_bytes())
        .unwrap();
}
